version: "3.7"

services:
  api:
    image: bluepigeon-backend:latest
    stdin_open: true
    tty: true
    networks:
      - root_default
    env_file: 
      - .env
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bluepigeon_be.rule=Host(`api.bluepigeon.ikutaja.id`)"
        - "traefik.http.routers.bluepigeon_be.entrypoints=websecure"
        - "traefik.http.routers.bluepigeon_be.tls.certresolver=letsencrypt"
        - "traefik.http.services.bluepigeon_be.loadbalancer.server.port=8080"

networks:
  root_default:
    external: true
